spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=faktureringskomponenten
    username: postgres
    password: mysecretpassword
  flyway:
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8084

cron:
  job:
    bestill-faktura:  "0 */5 * * * *" # Kjør hver 5 minutt


KAFKA_BROKERS: "localhost:29092"
KAFKA_KEYSTORE_PATH: "/dev/zero"
KAFKA_TRUSTSTORE_PATH: "/dev/zero"
KAFKA_CREDSTORE_PASSWORD: "pwd"
KAFKA_AIVEN_OEBS_FAKTURAMOTTATT_GROUPID: "faktura-mottatt-groupid"
KAFKA_AIVEN_OEBS_FAKTURAMOTTATT_TOPIC: "faktura-mottatt-topic"
KAFKA_TOPIC_NAME_FAKTURA_BESTILT: "faktura-bestilt.v1"
KAFKA_TOPIC_NAME_MANGLENDE_FAKTURABETALING: "manglende-fakturabetaling.v1"

AZURE_APP_WELL_KNOWN_URL: http://host.docker.internal:8082/isso/.well-known/openid-configuration
AZURE_APP_CLIENT_ID: melosys-localhost

unleash:
  token: "fake"

NAIS_CLUSTER_NAME: local
