spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

kafka:
  aiven:
    brokers: ${KAFKA_BROKERS}
    keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
    truststorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
    credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
  topics:
    producer:
      faktura-bestilt: ${KAFKA_TOPIC_NAME_FAKTURA_BESTILT}

#Token-validering
no.nav.security.jwt.issuer:
  aad:
    discovery-url: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    accepted-audience: srvmelosys
