spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

kafka:
  aiven:
    brokers: ${KAFKA_BROKERS}
    keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
    truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
    credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
  producer:
    faktura-bestilt: ${KAFKA_TOPIC_NAME_FAKTURA_BESTILT}
  consumer:
    oebs:
      groupid: ${KAFKA_AIVEN_OEBS_FAKTURAMOTTATT_GROUPID}
      topic: ${KAFKA_AIVEN_OEBS_FAKTURAMOTTATT_TOPIC}


#Token-validering
no.nav.security.jwt.issuer:
  aad:
    discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
    accepted-audience: ${AZURE_APP_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /internal