spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=faktureringskomponenten
    username: postgres
    password: mysecretpassword
  flyway:
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8084
