spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=faktureringskomponenten
    username: postgres
    password: mysecretpassword
  flyway:
    locations: classpath:db/migration

server:
  port: 8084

spring.jpa.hibernate.ddl-auto: create
spring.jpa.generate-ddl: true
