spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=faktureringskomponenten
    username: postgres
    password: mysecretpassword
  flyway:
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8084

kafka:
  aiven:
    brokers: "localhost:29092"
    keystorePath: "/dev/zero"
    truststorePath: "/dev/zero"
    credstorePassword: "pwd"
  topics:
    producer:
      faktura-bestilt: "faktura-bestilt.v1"

no.nav.security.jwt.issuer:
  reststs:
    discovery-url: http://localhost:8086/reststs/.well-known/openid-configuration
    accepted-audience: srvmelosys
  aad:
    discovery-url: http://host.docker.internal:8082/aad/.well-known/openid-configuration
    accepted-audience: melosys-localhost
