spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=faktureringskomponenten
    username: postgres
    password: mysecretpassword
  flyway:
    locations: classpath:db/migration

server:
  port: 8084

