apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app_name}}
  namespace: {{namespace}}
  labels:
    team: teammelosys
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: {{database_name}}
            envVarPrefix: DB
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/health
    initialDelay: 40
    timeout: 5
  readiness:
    path: /internal/health
    initialDelay: 35
    timeout: 5
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: {{app_name_melosys_api}}
          namespace: teammelosys
          cluster: {{cluster_name}}
          permissions:
            roles:
              - faktureringskomponenten-skriv
        - application: {{app_name_melosys_web}}
          namespace: teammelosys
          cluster: {{cluster_name}}
    outbound:
      external:
        - host: https://security-token-service.dev.adeo.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: KAFKA_TOPIC_NAME_FAKTURA_BESTILT
      value: {{kafka_topic_name_faktura_bestilt}}
    - name: KAFKA_TOPIC_NAME_MANGLENDE_FAKTURABETALING
      value: {{kafka_topic_name_manglende_fakturabetaling}}
  envFrom:
    - secret: faktureringskomponenten
