name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
      - MELOSYS-6952_7145_distroless
permissions:
  contents: write
  packages: write
env:
  image: ghcr.io/${{ github.repository }}/faktureringskomponenten
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PASSWORD: ${{ secrets.READER_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy new Unleash Apikey to ${{github.event.inputs.environment}}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/unleash-apitoken.yml
          VARS: nais/vars-q2.json
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup gradle dependency cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew clean build -x test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u THIS_IS_NOT_USED --password-stdin

      - name: Build and push multi-arch Docker image
        run: |
          versioned_image="${image}:${{ github.sha }}"
          latest_image="${image}:latest"

          # Build and push multi-architecture image
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push \
            --tag "$versioned_image" \
            --tag "$latest_image" \
            .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
#      - name: pre-deploy
#        uses: navikt/digihot-deploy/actions/pre-deploy@v2
      - name: Deploy til dev (Q2)
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yml
          VAR: image=${{env.image}}:${{ github.sha }}
          VARS: nais/vars-q2.json
      - name: Deploy til dev (Q1)
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yml
          VAR: image=${{env.image}}:${{ github.sha }}
          VARS: nais/vars-q1.json
      - name: Get commit message
        run: echo "COMMIT_MSG=$(git log --format=%s -n 1)" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: "faktureringskomponenten ${{ job.status == 'success' && 'ble deployet' || 'kunne ikke deployes' }} til dev-gcp (Q1, Q2)"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ env.COMMIT_MSG }}
#      - name: post-deploy
#        uses: navikt/digihot-deploy/actions/post-deploy@v2
#      - name: draft release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ env.VERSION_TAG }}
#          name: ${{ env.APPLICATION }} ${{ env.VERSION_TAG }}
#          body: ${{ env.CHANGE_LOG }}
#          draft: true
#          prerelease: false
