name: Gradle Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
      checks: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PASSWORD: ${{ secrets.READER_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/        


      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          check_name: 'Integration Tests'
          report_paths: '**/build/test-results/test/TEST-*.xml'