name: Gradle Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
      checks: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PASSWORD: ${{ secrets.READER_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: ./gradlew build

      - name: Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          check_name: 'Tests'
          report_paths: '**/build/test-results/test/TEST-*.xml'
